"""SQLite-backed sidecar store for episode embeddings (ADR-0009).

Episode log JSONL stays append-only and untouched. Embeddings are kept
in a separate SQLite file under MOLTBOOK_HOME so that:
  - JSONL audit trail and prompt-injection boundary are preserved
  - Embeddings can be regenerated by deleting the sidecar
  - Lookup is O(log n) via primary key index

Episode id is a stable hash of (ts, type, data_json), surviving file
renames and re-reads.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Tuple

import numpy as np

logger = logging.getLogger(__name__)


def episode_id_for(record: Dict) -> str:
    """Stable id for an episode record (first 16 chars of SHA-256)."""
    payload = json.dumps(
        {
            "ts": record.get("ts", ""),
            "type": record.get("type", ""),
            "data": record.get("data", {}),
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


class EpisodeEmbeddingStore:
    """SQLite store mapping episode_id → embedding vector.

    Vectors stored as raw numpy bytes (float32). Dimension is fixed by
    the embedding model in use; mixing dimensions across runs will
    silently corrupt cosine results, so callers should re-backfill if
    the model changes.
    """

    _SCHEMA = """
        CREATE TABLE IF NOT EXISTS episode_embeddings (
            episode_id TEXT PRIMARY KEY,
            ts TEXT NOT NULL,
            vector BLOB NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_ts ON episode_embeddings(ts);
    """

    def __init__(self, db_path: Optional[Path] = None) -> None:
        self._db_path = db_path
        self._initialized = False

    def _ensure_initialized(self) -> None:
        if self._initialized or self._db_path is None:
            self._initialized = True
            return
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        old_umask = os.umask(0o177)
        try:
            with self._connect() as conn:
                conn.executescript(self._SCHEMA)
        finally:
            os.umask(old_umask)
        self._initialized = True

    @contextmanager
    def _connect(self) -> Iterator[sqlite3.Connection]:
        if self._db_path is None:
            raise RuntimeError("EpisodeEmbeddingStore has no db_path configured")
        conn = sqlite3.connect(str(self._db_path))
        try:
            yield conn
            conn.commit()
        finally:
            conn.close()

    def upsert(self, episode_id: str, ts: str, vector: np.ndarray) -> None:
        """Insert or replace a single embedding."""
        self._ensure_initialized()
        if self._db_path is None:
            return
        blob = np.ascontiguousarray(vector, dtype=np.float32).tobytes()
        with self._connect() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO episode_embeddings (episode_id, ts, vector) VALUES (?, ?, ?)",
                (episode_id, ts, blob),
            )

    def upsert_many(self, items: Iterable[Tuple[str, str, np.ndarray]]) -> int:
        """Bulk insert/replace. Returns number of rows written."""
        self._ensure_initialized()
        if self._db_path is None:
            return 0
        rows = [
            (eid, ts, np.ascontiguousarray(vec, dtype=np.float32).tobytes())
            for eid, ts, vec in items
        ]
        if not rows:
            return 0
        with self._connect() as conn:
            conn.executemany(
                "INSERT OR REPLACE INTO episode_embeddings (episode_id, ts, vector) VALUES (?, ?, ?)",
                rows,
            )
        return len(rows)

    def get(self, episode_id: str) -> Optional[np.ndarray]:
        """Fetch one embedding by id, or None if not present."""
        self._ensure_initialized()
        if self._db_path is None or not self._db_path.exists():
            return None
        with self._connect() as conn:
            row = conn.execute(
                "SELECT vector FROM episode_embeddings WHERE episode_id = ?",
                (episode_id,),
            ).fetchone()
        if row is None:
            return None
        return np.frombuffer(row[0], dtype=np.float32)

    def get_many(self, episode_ids: List[str]) -> Dict[str, np.ndarray]:
        """Bulk fetch. Missing ids are absent from the result dict."""
        self._ensure_initialized()
        if self._db_path is None or not self._db_path.exists() or not episode_ids:
            return {}
        placeholders = ",".join("?" * len(episode_ids))
        with self._connect() as conn:
            rows = conn.execute(
                f"SELECT episode_id, vector FROM episode_embeddings WHERE episode_id IN ({placeholders})",
                episode_ids,
            ).fetchall()
        return {eid: np.frombuffer(blob, dtype=np.float32) for eid, blob in rows}

    def has(self, episode_id: str) -> bool:
        return self.get(episode_id) is not None

    def count(self) -> int:
        self._ensure_initialized()
        if self._db_path is None or not self._db_path.exists():
            return 0
        with self._connect() as conn:
            row = conn.execute(
                "SELECT COUNT(*) FROM episode_embeddings"
            ).fetchone()
        return int(row[0]) if row else 0

    def clear(self) -> None:
        """Drop all rows. Used by tests and embed-backfill regeneration."""
        self._ensure_initialized()
        if self._db_path is None or not self._db_path.exists():
            return
        with self._connect() as conn:
            conn.execute("DELETE FROM episode_embeddings")
