"""Rules distillation: synthesize behavioral skills into universal rules.

Two-stage LLM pipeline (ADR-0008): free-form extraction → structured Markdown.
Input: skills/*.md files generated by ``insight``.
Human in the loop — this command is never auto-scheduled.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import List, Optional, Tuple, Union

from .insight import _extract_title, _slugify
from .llm import generate, get_distill_system_prompt, validate_identity_content
from .prompts import RULES_DISTILL_PROMPT, RULES_DISTILL_REFINE_PROMPT

logger = logging.getLogger(__name__)

MIN_SKILLS_REQUIRED = 3
# Number of skill files passed to one LLM extraction call. This is NOT the
# same as insight's BATCH_SIZE (patterns per subcategory) — here it's the
# breadth of input across which the LLM searches for cross-cutting universal
# principles. Renamed from BATCH_SIZE to avoid confusion with insight.py.
SKILLS_PER_BATCH = 10


@dataclass(frozen=True)
class RuleResult:
    """A single generated rule ready for approval."""

    text: str
    filename: str
    target_path: Path


@dataclass(frozen=True)
class RulesDistillResult:
    """Result of a successful rules distillation."""

    rules: Tuple[RuleResult, ...]
    dropped_count: int
    rules_dir: Path


def _strip_frontmatter(text: str) -> str:
    """Strip YAML frontmatter (``---`` delimited) from Markdown text."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return text
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "\n".join(lines[i + 1 :]).lstrip("\n")
    return text


def _read_skills(skills_dir: Path, since: Optional[str] = None) -> List[str]:
    """Read skill file contents from *skills_dir*.

    Args:
        skills_dir: Directory containing ``*.md`` skill files.
        since: ISO timestamp — only include files modified after this time.

    Returns:
        List of skill file body texts (frontmatter stripped).
    """
    if not skills_dir.is_dir():
        return []

    cutoff: Optional[float] = None
    if since:
        try:
            cutoff = datetime.fromisoformat(since).timestamp()
        except ValueError:
            logger.warning("Invalid since timestamp %r, reading all skills", since)

    skills: List[str] = []
    for p in sorted(skills_dir.glob("*.md")):
        if p.name.startswith("."):
            continue
        if cutoff is not None and p.stat().st_mtime < cutoff:
            continue
        try:
            body = _strip_frontmatter(p.read_text(encoding="utf-8")).strip()
            if body:
                skills.append(body)
        except OSError:
            logger.warning("Could not read skill file %s", p)
    return skills


# Marker the refine prompt emits when Stage 1 analysis found 0 passing
# principles. Treated as a valid (empty) result rather than an error.
_NO_RULES_MARKER = "# No Universal Rules Found"


def _extract_rules(skill_texts: List[str]) -> Optional[str]:
    """Extract behavioral rules from skill texts via 2-stage LLM pipeline.

    Stage 1: Free-form extraction with distill system prompt as lens.
    Stage 2: Refine into structured Markdown.

    Returns the Stage 2 Markdown, or None on LLM failure / invalid output.
    An empty-but-valid result (no universal rules in this batch) returns
    the ``_NO_RULES_MARKER`` string which callers should recognize.
    """
    prompt = RULES_DISTILL_PROMPT.format(
        patterns="\n\n---\n\n".join(skill_texts),
    )

    raw = generate(prompt, system=get_distill_system_prompt(), num_predict=1500)
    if raw is None:
        logger.warning("Stage 1 (extraction) failed.")
        return None

    refine_prompt = RULES_DISTILL_REFINE_PROMPT.format(raw_output=raw)
    result = generate(refine_prompt, num_predict=1500)
    if result is None:
        logger.warning("Stage 2 (refinement) failed.")
        return None

    # "No Universal Rules Found" is a valid outcome — the Stage 1 analysis
    # concluded that no candidate principle passed all four universality
    # tests for this batch. Propagate as-is so the caller records 0 rules.
    if result.strip().startswith(_NO_RULES_MARKER):
        logger.info("Stage 2: no universal rules passed for this batch.")
        return _NO_RULES_MARKER

    if _extract_title(result) is None:
        logger.warning("Rules extraction has no title (# line). Dropping.")
        logger.debug("Raw LLM output (first 200 chars): %.200s", result)
        return None

    return result


def _split_rules(text: str) -> List[str]:
    """Split a multi-rule document into individual rule texts.

    The LLM produces output like:
        # Rule Set Title
        ## Rule 1: Name
        **When:** ...
        ## Rule 2: Name
        **When:** ...

    This splits on ``## Rule`` boundaries and gives each chunk
    a ``# Rule: {name}`` title for independent use.
    """
    import re

    parts = re.split(r"(?=^## Rule \d+)", text, flags=re.MULTILINE)
    rules: List[str] = []
    for part in parts:
        part = part.strip()
        if not part or not part.startswith("## Rule"):
            continue
        # Extract rule name from "## Rule N: Name"
        match = re.match(r"^## Rule \d+:\s*(.+)", part)
        name = match.group(1).strip() if match else "Untitled Rule"
        # Replace ## with # for standalone title
        rule_text = f"# {name}\n\n" + re.sub(r"^## Rule \d+:.*\n*", "", part, count=1).strip()
        if rule_text.strip():
            rules.append(rule_text)
    return rules


def _read_last_run(rules_dir: Optional[Path]) -> Optional[str]:
    """Read the timestamp of the last rules-distill run."""
    if rules_dir is None:
        return None
    marker = rules_dir / ".last_rules_distill"
    if marker.exists():
        return marker.read_text(encoding="utf-8").strip()
    return None


def _write_last_run(rules_dir: Path) -> None:
    """Record the current timestamp as the last rules-distill run."""
    rules_dir.mkdir(parents=True, exist_ok=True)
    marker = rules_dir / ".last_rules_distill"
    marker.write_text(
        datetime.now(timezone.utc).isoformat(timespec="minutes") + "\n",
        encoding="utf-8",
    )


def distill_rules(
    skills_dir: Optional[Path] = None,
    rules_dir: Optional[Path] = None,
    full: bool = False,
) -> Union[str, RulesDistillResult]:
    """Distill universal behavioral rules from accumulated skill files.

    Two-stage pipeline per batch: free-form extraction → structured Markdown.
    Reads skills/*.md generated by ``insight``.

    File writing is the caller's responsibility (ADR-0012 approval gate).

    Args:
        skills_dir: Directory containing skill files (``*.md``).
        rules_dir: Directory for rule files (used for incremental tracking).
        full: If True, process all skills instead of only new ones.

    Returns:
        RulesDistillResult on success, or error message string.
    """
    if skills_dir is None:
        return "No skills directory provided."

    since: Optional[str] = None
    if not full:
        since = _read_last_run(rules_dir)
        if since:
            logger.info("Incremental mode: reading skills modified since %s", since)

    skill_texts = _read_skills(skills_dir, since=since)

    if not since and not full:
        logger.info("No previous rules-distill run found, processing all %d skills", len(skill_texts))

    if len(skill_texts) < MIN_SKILLS_REQUIRED:
        return (
            f"Insufficient skills ({len(skill_texts)}/{MIN_SKILLS_REQUIRED}). "
            f"Universal principles require a critical mass of behavioral skills."
        )

    batches = [
        skill_texts[i : i + SKILLS_PER_BATCH]
        for i in range(0, len(skill_texts), SKILLS_PER_BATCH)
    ]
    if len(batches) > 1 and len(batches[-1]) < MIN_SKILLS_REQUIRED:
        batches[-2].extend(batches[-1])
        batches.pop()

    logger.info(
        "Processing %d skills in %d batches", len(skill_texts), len(batches)
    )

    rule_results: List[RuleResult] = []
    dropped_count = 0
    empty_batches = 0  # Batches that correctly returned "no universal rules"

    for batch_idx, batch in enumerate(batches):
        logger.info(
            "Batch %d/%d: %d skills", batch_idx + 1, len(batches), len(batch)
        )

        rules_text = _extract_rules(batch)
        if rules_text is None:
            logger.warning("Batch %d/%d: extraction failed", batch_idx + 1, len(batches))
            dropped_count += 1
            continue

        # Valid empty outcome: Stage 2 found no principle worth keeping.
        # Not an error, just nothing to persist for this batch.
        if rules_text == _NO_RULES_MARKER:
            logger.info(
                "Batch %d/%d: no universal rules (by design)",
                batch_idx + 1,
                len(batches),
            )
            empty_batches += 1
            continue

        individual_rules = _split_rules(rules_text)
        if not individual_rules:
            # Fallback: treat entire text as single rule if split fails
            individual_rules = [rules_text]

        today = date.today().strftime("%Y%m%d")
        for rule_text in individual_rules:
            if not validate_identity_content(rule_text):
                logger.warning("Batch %d/%d: forbidden pattern in rule, dropping", batch_idx + 1, len(batches))
                dropped_count += 1
                continue

            title = _extract_title(rule_text) or ""
            slug = _slugify(title)
            if not slug:
                logger.warning("Batch %d/%d: empty slug, dropping", batch_idx + 1, len(batches))
                dropped_count += 1
                continue

            filename = f"{slug}-{today}.md"

            if rules_dir is not None:
                file_path = rules_dir / filename
                if not file_path.resolve().is_relative_to(rules_dir.resolve()):
                    logger.error("Rule path escape attempt: %s", file_path)
                    dropped_count += 1
                    continue
            else:
                file_path = Path(filename)

            rule_results.append(RuleResult(
                text=rule_text,
                filename=filename,
                target_path=file_path,
            ))

    if not rule_results:
        # Distinguish "LLM failed to produce anything" from "LLM correctly
        # judged that no universal principle exists in this set of skills".
        # Both result in 0 rules, but the meaning (and what the user should
        # do next) is very different.
        if empty_batches == len(batches) and dropped_count == 0:
            return (
                f"No universal rules extracted. All {empty_batches} batch(es) "
                f"determined that no principle passes the four universality "
                f"tests for the current skill set. This is a valid outcome; "
                f"accumulate more diverse skills and try again."
            )
        return "Failed to extract rules from skills."

    return RulesDistillResult(
        rules=tuple(rule_results),
        dropped_count=dropped_count,
        rules_dir=rules_dir or Path("."),
    )
